"""Render a captured span tree as an SVG waterfall.

The README wants a picture of a trace, and the obvious way to get one is a
screenshot of Phoenix. A screenshot is the wrong artefact for this repository:
it goes stale the moment the graph changes, nobody can tell whether it was
taken from the run that produced the numbers beside it, and it cannot be
regenerated by anyone reading the file. This reads the same JSON that
``python -m filing.eval trace`` writes and draws it, so the picture is a
function of the committed evidence rather than a memory of it.

    python scripts/render_trace.py docs/trace_repair.json docs/trace.svg

One layout assumption, and it is checked rather than assumed: the agent graph
runs its nodes one after another, so a child's start is the sum of its earlier
siblings' durations. ``_check`` compares that sum against the parent's own
duration and refuses to draw if they disagree by more than 5%, which is what
would happen if the graph ever went concurrent and the picture quietly started
lying about when things ran.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# A hue per stage, assigned by what the stage *does* rather than by position, so
# the two passes of a repair loop are visibly the same two stages twice.
COLORS = {
    "plan": "#6b5bd2",
    "route": "#8a8f98",
    "retrieve": "#2f8f6b",
    "rerank": "#3d7fb8",
    "grade": "#c98a2b",
    "repair": "#c05a4a",
    "synthesise": "#6b5bd2",
    "verify": "#c05a4a",
    "question": "#4a4f57",
}
INK = "#1c1f23"
MUTED = "#6b7280"
GRID = "#dfe3e8"
CARD = "#ffffff"

ROW = 26
PAD_TOP = 84
PAD_BOTTOM = 34
LABEL_W = 210
BAR_W = 470
LEFT = 18


def _hue(name: str) -> str:
    tail = name.split(".")[-1]
    for key, color in COLORS.items():
        if key in tail or key in name:
            return color
    return COLORS["question"]


def _flatten(node: dict, depth: int = 0, start: float = 0.0, out: list | None = None) -> list:
    out = [] if out is None else out
    out.append({"name": node["name"], "ms": float(node["ms"]), "depth": depth, "start": start})
    cursor = start
    for child in node.get("children", ()):
        _flatten(child, depth + 1, cursor, out)
        cursor += float(child["ms"])
    return out


def _check(node: dict) -> None:
    kids = node.get("children", ())
    if not kids:
        return
    total = sum(float(c["ms"]) for c in kids)
    parent = float(node["ms"])
    if parent and abs(total - parent) / parent > 0.05:
        raise SystemExit(
            f"{node['name']}: children sum to {total:.0f}ms inside a {parent:.0f}ms parent. "
            "The sequential layout this renderer assumes no longer holds -- if the graph "
            "now runs nodes concurrently, the drawing needs real start timestamps."
        )
    for child in kids:
        _check(child)


def _esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render(trace: dict) -> str:
    root = trace["spans"][0]
    _check(root)
    rows = _flatten(root)
    span_ms = max(r["start"] + r["ms"] for r in rows) or 1.0
    width = LEFT * 2 + LABEL_W + BAR_W + 76
    height = PAD_TOP + ROW * len(rows) + PAD_BOTTOM

    def x(ms: float) -> float:
        return LEFT + LABEL_W + (ms / span_ms) * BAR_W

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" font-family="ui-monospace,SFMono-Regular,'
        f'Menlo,Consolas,monospace" role="img" aria-label="agent span waterfall">',
        f'<rect width="{width}" height="{height}" rx="8" fill="{CARD}"/>',
        f'<text x="{LEFT}" y="26" font-size="13" font-weight="600" fill="{INK}">'
        f"{_esc(trace['qid'])} &#183; route {_esc(trace['route'])} &#183; "
        f"{trace['repairs']} repair(s) &#183; {trace['llm_calls']} LLM calls</text>",
        f'<text x="{LEFT}" y="44" font-size="11" fill="{MUTED}">'
        f"{_esc(trace['question'][:78])}</text>",
    ]

    # Four ticks. Enough to read a duration off the drawing, few enough that the
    # gridlines stay behind the bars rather than competing with them.
    for i in range(5):
        ms = span_ms * i / 4
        parts.append(
            f'<line x1="{x(ms):.1f}" y1="{PAD_TOP - 12}" x2="{x(ms):.1f}" '
            f'y2="{PAD_TOP + ROW * len(rows)}" stroke="{GRID}" stroke-width="1"/>'
        )
        parts.append(
            f'<text x="{x(ms):.1f}" y="{PAD_TOP - 18}" font-size="9" fill="{MUTED}" '
            f'text-anchor="middle">{ms / 1000:.1f}s</text>'
        )

    for i, row in enumerate(rows):
        y = PAD_TOP + i * ROW
        indent = LEFT + row["depth"] * 12
        parts.append(
            f'<text x="{indent}" y="{y + 15}" font-size="11" fill="{INK}">'
            f"{_esc(row['name'])}</text>"
        )
        # A zero-millisecond node is still a node that ran; 2px of bar says so
        # without pretending it took measurable time.
        bar = max((row["ms"] / span_ms) * BAR_W, 2.0)
        parts.append(
            f'<rect x="{x(row["start"]):.1f}" y="{y + 5}" width="{bar:.1f}" height="13" '
            f'rx="3" fill="{_hue(row["name"])}"/>'
        )
        parts.append(
            f'<text x="{x(row["start"]) + bar + 6:.1f}" y="{y + 15}" font-size="10" '
            f'fill="{MUTED}">{row["ms"]:.0f}ms</text>'
        )

    parts.append(
        f'<text x="{LEFT}" y="{height - 12}" font-size="10" fill="{MUTED}">'
        f"{float(trace['seconds']):.2f}s wall clock &#183; regenerate with "
        f"python scripts/render_trace.py</text>"
    )
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__.strip().splitlines()[0])
        print("usage: python scripts/render_trace.py <trace.json> <out.svg>")
        return 2
    trace = json.loads(Path(argv[1]).read_text(encoding="utf-8"))
    out = Path(argv[2])
    out.write_text(render(trace), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
